"""
City-level solar, rainfall, and energy parameter lookup table.
Sources: MNRE Solar Radiation Handbook, IMD long-period rainfall averages,
CPCB/CGWB Rainwater Harvesting Manual, state electricity tariff orders.
"""

CITY_PARAMETERS = {
    # ── DEFAULT ──────────────────────────────────────────────────────────────
    "default": {
        "ghi_kwh_per_sqm_per_day": 5.30,
        "annual_rainfall_mm": 1100,
        "electricity_tariff_inr_kwh": 8.0,
        "water_cost_inr_kl": 20.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── MAHARASHTRA ───────────────────────────────────────────────────────────
    "mumbai": {
        "ghi_kwh_per_sqm_per_day": 5.20,
        "annual_rainfall_mm": 2400,
        "electricity_tariff_inr_kwh": 10.0,
        "water_cost_inr_kl": 17.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "pune": {
        "ghi_kwh_per_sqm_per_day": 5.40,
        "annual_rainfall_mm": 720,
        "electricity_tariff_inr_kwh": 9.5,
        "water_cost_inr_kl": 18.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "nagpur": {
        "ghi_kwh_per_sqm_per_day": 5.50,
        "annual_rainfall_mm": 1100,
        "electricity_tariff_inr_kwh": 8.5,
        "water_cost_inr_kl": 15.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "nashik": {
        "ghi_kwh_per_sqm_per_day": 5.4,
        "annual_rainfall_mm": 694,
        "electricity_tariff_inr_kwh": 9.0,
        "water_cost_inr_kl": 16.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "aurangabad": {
        "ghi_kwh_per_sqm_per_day": 5.5,
        "annual_rainfall_mm": 726,
        "electricity_tariff_inr_kwh": 8.5,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── KARNATAKA ─────────────────────────────────────────────────────────────
    "bengaluru": {
        "ghi_kwh_per_sqm_per_day": 5.50,
        "annual_rainfall_mm": 970,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 22.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "bangalore": {
        "ghi_kwh_per_sqm_per_day": 5.50,
        "annual_rainfall_mm": 970,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 22.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "mysuru": {
        "ghi_kwh_per_sqm_per_day": 5.6,
        "annual_rainfall_mm": 787,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 18.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "mysore": {
        "ghi_kwh_per_sqm_per_day": 5.6,
        "annual_rainfall_mm": 787,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 18.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "hubli": {
        "ghi_kwh_per_sqm_per_day": 5.7,
        "annual_rainfall_mm": 590,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "mangaluru": {
        "ghi_kwh_per_sqm_per_day": 4.8,
        "annual_rainfall_mm": 3430,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 16.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── TAMIL NADU ────────────────────────────────────────────────────────────
    "chennai": {
        "ghi_kwh_per_sqm_per_day": 5.50,
        "annual_rainfall_mm": 1400,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 9.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "coimbatore": {
        "ghi_kwh_per_sqm_per_day": 5.60,
        "annual_rainfall_mm": 650,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "madurai": {
        "ghi_kwh_per_sqm_per_day": 5.70,
        "annual_rainfall_mm": 850,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "tiruchirappalli": {
        "ghi_kwh_per_sqm_per_day": 5.8,
        "annual_rainfall_mm": 843,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "salem": {
        "ghi_kwh_per_sqm_per_day": 5.7,
        "annual_rainfall_mm": 923,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── TELANGANA / ANDHRA PRADESH ────────────────────────────────────────────
    "hyderabad": {
        "ghi_kwh_per_sqm_per_day": 5.60,
        "annual_rainfall_mm": 800,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 15.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "secunderabad": {
        "ghi_kwh_per_sqm_per_day": 5.60,
        "annual_rainfall_mm": 800,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 15.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "visakhapatnam": {
        "ghi_kwh_per_sqm_per_day": 5.40,
        "annual_rainfall_mm": 1050,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "vijayawada": {
        "ghi_kwh_per_sqm_per_day": 5.50,
        "annual_rainfall_mm": 950,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "warangal": {
        "ghi_kwh_per_sqm_per_day": 5.5,
        "annual_rainfall_mm": 1004,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 13.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── KERALA ────────────────────────────────────────────────────────────────
    "kochi": {
        "ghi_kwh_per_sqm_per_day": 5.20,
        "annual_rainfall_mm": 3100,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "thiruvananthapuram": {
        "ghi_kwh_per_sqm_per_day": 5.30,
        "annual_rainfall_mm": 1700,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "kozhikode": {
        "ghi_kwh_per_sqm_per_day": 4.7,
        "annual_rainfall_mm": 2950,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "thrissur": {
        "ghi_kwh_per_sqm_per_day": 4.9,
        "annual_rainfall_mm": 2800,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── DELHI / NCR ───────────────────────────────────────────────────────────
    "delhi": {
        "ghi_kwh_per_sqm_per_day": 5.30,
        "annual_rainfall_mm": 770,
        "electricity_tariff_inr_kwh": 8.0,
        "water_cost_inr_kl": 5.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "new delhi": {
        "ghi_kwh_per_sqm_per_day": 5.30,
        "annual_rainfall_mm": 770,
        "electricity_tariff_inr_kwh": 8.0,
        "water_cost_inr_kl": 5.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "gurgaon": {
        "ghi_kwh_per_sqm_per_day": 5.30,
        "annual_rainfall_mm": 750,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "gurugram": {
        "ghi_kwh_per_sqm_per_day": 5.30,
        "annual_rainfall_mm": 750,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "noida": {
        "ghi_kwh_per_sqm_per_day": 5.25,
        "annual_rainfall_mm": 760,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "faridabad": {
        "ghi_kwh_per_sqm_per_day": 5.30,
        "annual_rainfall_mm": 750,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "ghaziabad": {
        "ghi_kwh_per_sqm_per_day": 5.25,
        "annual_rainfall_mm": 760,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── UTTAR PRADESH ─────────────────────────────────────────────────────────
    "lucknow": {
        "ghi_kwh_per_sqm_per_day": 5.20,
        "annual_rainfall_mm": 950,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "kanpur": {
        "ghi_kwh_per_sqm_per_day": 5.1,
        "annual_rainfall_mm": 812,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "agra": {
        "ghi_kwh_per_sqm_per_day": 5.3,
        "annual_rainfall_mm": 688,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "varanasi": {
        "ghi_kwh_per_sqm_per_day": 5.1,
        "annual_rainfall_mm": 1110,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "allahabad": {
        "ghi_kwh_per_sqm_per_day": 5.1,
        "annual_rainfall_mm": 1011,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "prayagraj": {
        "ghi_kwh_per_sqm_per_day": 5.1,
        "annual_rainfall_mm": 1011,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── RAJASTHAN ─────────────────────────────────────────────────────────────
    "jaipur": {
        "ghi_kwh_per_sqm_per_day": 5.70,
        "annual_rainfall_mm": 650,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "jodhpur": {
        "ghi_kwh_per_sqm_per_day": 6.2,
        "annual_rainfall_mm": 357,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 16.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "udaipur": {
        "ghi_kwh_per_sqm_per_day": 5.8,
        "annual_rainfall_mm": 637,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "kota": {
        "ghi_kwh_per_sqm_per_day": 5.8,
        "annual_rainfall_mm": 675,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 13.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── GUJARAT ───────────────────────────────────────────────────────────────
    "ahmedabad": {
        "ghi_kwh_per_sqm_per_day": 5.80,
        "annual_rainfall_mm": 800,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 13.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "surat": {
        "ghi_kwh_per_sqm_per_day": 5.75,
        "annual_rainfall_mm": 1150,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "vadodara": {
        "ghi_kwh_per_sqm_per_day": 5.75,
        "annual_rainfall_mm": 950,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "rajkot": {
        "ghi_kwh_per_sqm_per_day": 5.80,
        "annual_rainfall_mm": 600,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── MADHYA PRADESH ────────────────────────────────────────────────────────
    "bhopal": {
        "ghi_kwh_per_sqm_per_day": 5.40,
        "annual_rainfall_mm": 1150,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 13.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 90.0,
    },
    "indore": {
        "ghi_kwh_per_sqm_per_day": 5.50,
        "annual_rainfall_mm": 950,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "jabalpur": {
        "ghi_kwh_per_sqm_per_day": 5.3,
        "annual_rainfall_mm": 1440,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "gwalior": {
        "ghi_kwh_per_sqm_per_day": 5.4,
        "annual_rainfall_mm": 759,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── PUNJAB / HARYANA / HIMACHAL ───────────────────────────────────────────
    "chandigarh": {
        "ghi_kwh_per_sqm_per_day": 4.8,
        "annual_rainfall_mm": 1110,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 8.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "ludhiana": {
        "ghi_kwh_per_sqm_per_day": 4.8,
        "annual_rainfall_mm": 750,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "amritsar": {
        "ghi_kwh_per_sqm_per_day": 4.9,
        "annual_rainfall_mm": 682,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "shimla": {
        "ghi_kwh_per_sqm_per_day": 4.2,
        "annual_rainfall_mm": 1575,
        "electricity_tariff_inr_kwh": 4.5,
        "water_cost_inr_kl": 8.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── BIHAR / JHARKHAND ─────────────────────────────────────────────────────
    "patna": {
        "ghi_kwh_per_sqm_per_day": 5.0,
        "annual_rainfall_mm": 1200,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "ranchi": {
        "ghi_kwh_per_sqm_per_day": 4.9,
        "annual_rainfall_mm": 1430,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── WEST BENGAL / ODISHA ──────────────────────────────────────────────────
    "kolkata": {
        "ghi_kwh_per_sqm_per_day": 4.80,
        "annual_rainfall_mm": 1750,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 6.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "bhubaneswar": {
        "ghi_kwh_per_sqm_per_day": 5.2,
        "annual_rainfall_mm": 1533,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── ASSAM / NORTH EAST ────────────────────────────────────────────────────
    "guwahati": {
        "ghi_kwh_per_sqm_per_day": 4.5,
        "annual_rainfall_mm": 1600,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 8.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── GOA ───────────────────────────────────────────────────────────────────
    "panaji": {
        "ghi_kwh_per_sqm_per_day": 5.0,
        "annual_rainfall_mm": 2932,
        "electricity_tariff_inr_kwh": 3.5,
        "water_cost_inr_kl": 8.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "goa": {
        "ghi_kwh_per_sqm_per_day": 5.0,
        "annual_rainfall_mm": 2932,
        "electricity_tariff_inr_kwh": 3.5,
        "water_cost_inr_kl": 8.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── CHHATTISGARH ──────────────────────────────────────────────────────────
    "raipur": {
        "ghi_kwh_per_sqm_per_day": 5.2,
        "annual_rainfall_mm": 1340,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── UTTARAKHAND ───────────────────────────────────────────────────────────
    "dehradun": {
        "ghi_kwh_per_sqm_per_day": 4.8,
        "annual_rainfall_mm": 2073,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 9.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── JAMMU & KASHMIR / LADAKH ──────────────────────────────────────────────
    "jammu": {
        "ghi_kwh_per_sqm_per_day": 5.0,
        "annual_rainfall_mm": 1100,
        "electricity_tariff_inr_kwh": 4.0,
        "water_cost_inr_kl": 7.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "srinagar": {
        "ghi_kwh_per_sqm_per_day": 4.5,
        "annual_rainfall_mm": 730,
        "electricity_tariff_inr_kwh": 4.0,
        "water_cost_inr_kl": 7.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "leh": {
        "ghi_kwh_per_sqm_per_day": 6.0,
        "annual_rainfall_mm": 90,
        "electricity_tariff_inr_kwh": 4.0,
        "water_cost_inr_kl": 6.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    # ── ADDITIONAL TIER-2 CITIES ──────────────────────────────────────────────
    "thane": {
        "ghi_kwh_per_sqm_per_day": 5.20,
        "annual_rainfall_mm": 2400,
        "electricity_tariff_inr_kwh": 9.5,
        "water_cost_inr_kl": 16.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "navi mumbai": {
        "ghi_kwh_per_sqm_per_day": 5.20,
        "annual_rainfall_mm": 2300,
        "electricity_tariff_inr_kwh": 9.5,
        "water_cost_inr_kl": 16.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "kolhapur": {
        "ghi_kwh_per_sqm_per_day": 5.3,
        "annual_rainfall_mm": 977,
        "electricity_tariff_inr_kwh": 9.0,
        "water_cost_inr_kl": 15.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "solapur": {
        "ghi_kwh_per_sqm_per_day": 5.6,
        "annual_rainfall_mm": 615,
        "electricity_tariff_inr_kwh": 9.0,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "belgaum": {
        "ghi_kwh_per_sqm_per_day": 5.5,
        "annual_rainfall_mm": 800,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "belagavi": {
        "ghi_kwh_per_sqm_per_day": 5.5,
        "annual_rainfall_mm": 800,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 14.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "tirunelveli": {
        "ghi_kwh_per_sqm_per_day": 5.9,
        "annual_rainfall_mm": 692,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "erode": {
        "ghi_kwh_per_sqm_per_day": 5.8,
        "annual_rainfall_mm": 790,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "vellore": {
        "ghi_kwh_per_sqm_per_day": 5.7,
        "annual_rainfall_mm": 1000,
        "electricity_tariff_inr_kwh": 6.0,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "nellore": {
        "ghi_kwh_per_sqm_per_day": 5.6,
        "annual_rainfall_mm": 987,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "guntur": {
        "ghi_kwh_per_sqm_per_day": 5.5,
        "annual_rainfall_mm": 1000,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "tirupati": {
        "ghi_kwh_per_sqm_per_day": 5.7,
        "annual_rainfall_mm": 928,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 11.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "kolapur": {
        "ghi_kwh_per_sqm_per_day": 5.3,
        "annual_rainfall_mm": 977,
        "electricity_tariff_inr_kwh": 9.0,
        "water_cost_inr_kl": 15.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "bikaner": {
        "ghi_kwh_per_sqm_per_day": 6.3,
        "annual_rainfall_mm": 292,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 18.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "ajmer": {
        "ghi_kwh_per_sqm_per_day": 5.9,
        "annual_rainfall_mm": 503,
        "electricity_tariff_inr_kwh": 7.5,
        "water_cost_inr_kl": 15.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "gandhinagar": {
        "ghi_kwh_per_sqm_per_day": 5.8,
        "annual_rainfall_mm": 780,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "anand": {
        "ghi_kwh_per_sqm_per_day": 5.7,
        "annual_rainfall_mm": 850,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 12.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "dhanbad": {
        "ghi_kwh_per_sqm_per_day": 4.9,
        "annual_rainfall_mm": 1370,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "jamshedpur": {
        "ghi_kwh_per_sqm_per_day": 4.9,
        "annual_rainfall_mm": 1200,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "durgapur": {
        "ghi_kwh_per_sqm_per_day": 4.8,
        "annual_rainfall_mm": 1400,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 8.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "siliguri": {
        "ghi_kwh_per_sqm_per_day": 4.2,
        "annual_rainfall_mm": 3000,
        "electricity_tariff_inr_kwh": 7.0,
        "water_cost_inr_kl": 8.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "meerut": {
        "ghi_kwh_per_sqm_per_day": 5.1,
        "annual_rainfall_mm": 860,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "bareilly": {
        "ghi_kwh_per_sqm_per_day": 5.0,
        "annual_rainfall_mm": 1010,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "aligarh": {
        "ghi_kwh_per_sqm_per_day": 5.2,
        "annual_rainfall_mm": 780,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "moradabad": {
        "ghi_kwh_per_sqm_per_day": 5.0,
        "annual_rainfall_mm": 910,
        "electricity_tariff_inr_kwh": 6.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
    "raipur": {
        "ghi_kwh_per_sqm_per_day": 5.2,
        "annual_rainfall_mm": 1340,
        "electricity_tariff_inr_kwh": 5.5,
        "water_cost_inr_kl": 10.0,
        "lpg_domestic_inr_kg": 64.0,
        "lpg_commercial_inr_kg": 80.0,
    },
}


def get_city_params(city: str) -> dict:
    return CITY_PARAMETERS.get((city or "").lower().strip(), CITY_PARAMETERS["default"])


async def seed_city_parameters(db):
    for city_id, params in CITY_PARAMETERS.items():
        await db.city_parameters.update_one(
            {"city_id": city_id},
            {"$set": {**params, "city_id": city_id}},
            upsert=True,
        )
