// Parses the 9-section deterministic markdown report generated by generate_report_from_templates()
export function parseReportSections(reportText) {
  if (!reportText) return { parsedOk: false, raw: '' };
  const HEADER_RE = /(?:^|\n)[ \t]*(?:#{1,3}[ \t]+)?(?:\*{1,2})?(\d+)\.[ \t]+([^\n*#]{3,80}?)(?:\*{1,2})?[ \t]*(?=\n|$)/g;
  const headers = [];
  let m;
  while ((m = HEADER_RE.exec(reportText)) !== null) {
    headers.push({ num: parseInt(m[1]), headerStart: m.index, headerEnd: m.index + m[0].length });
  }
  if (headers.length < 3) return { parsedOk: false, raw: reportText };
  const sec = {};
  for (let i = 0; i < headers.length; i++) {
    const start = headers[i].headerEnd;
    const end   = i + 1 < headers.length ? headers[i + 1].headerStart : reportText.length;
    sec[headers[i].num] = reportText.slice(start, end).trim();
  }
  return {
    parsedOk:        true,
    raw:             reportText,
    profile:         sec[1] || '',
    readiness:       sec[2] || '',
    strengths:       sec[3] || '',
    gapAnalysis:     sec[4] || '',
    recommendations: sec[5] || '',
    savings:         sec[6] || '',
    roadmap:         sec[7] || '',
    support:         sec[8] || '',
    finalAssessment: sec[9] || '',
  };
}

export function extractBullets(text, max = 3) {
  if (!text) return [];
  const out = [];
  for (const line of text.split('\n')) {
    if (out.length >= max) break;
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const bm = t.match(/^[-*•✓]\s+(.+)$/) || t.match(/^\d+[.)]\s+(.+)$/);
    if (bm) out.push(bm[1].trim());
  }
  return out;
}

export function extractPhases(roadmapText) {
  if (!roadmapText) return [[], [], []];
  const PHASE_RE = /(?:^|\n)[ \t]*(?:#{1,3}[ \t]+)?(?:\*{0,2})?(?:Phase\s*[123]|PHASE\s*[123])(?:\*{0,2})?[ \t]*:?[^\n]*(?=\n|$)/gi;
  const splits = [];
  let pm;
  while ((pm = PHASE_RE.exec(roadmapText)) !== null) splits.push(pm.index + pm[0].length);
  if (splits.length >= 3) {
    return [
      extractBullets(roadmapText.slice(splits[0], splits[1]), 4),
      extractBullets(roadmapText.slice(splits[1], splits[2]), 4),
      extractBullets(roadmapText.slice(splits[2]), 4),
    ];
  }
  const all = extractBullets(roadmapText, 12);
  return [all.slice(0, 4), all.slice(4, 8), all.slice(8, 12)];
}
